
# Consulta SQL


#Filtro SQL

SELECT ESTU_CONSECUTIVO,
       COLE_COD_DANE_ESTABLECIMIENTO,
       COLE_BILINGUE,
       COLE_CALENDARIO,
       COLE_JORNADA,
       FAMI_CUARTOSHOGAR,
       FAMI_EDUCACIONMADRE,
       FAMI_EDUCACIONPADRE,
       FAMI_ESTRATOVIVIENDA,
       FAMI_PERSONASHOGAR,
       FAMI_TIENEAUTOMOVIL,
       FAMI_TIENECOMPUTADOR,
       FAMI_TIENEINTERNET,
       FAMI_TIENELAVADORA,
       DESEMP_INGLES,
       PUNT_INGLES,
       PUNT_MATEMATICAS,
       PUNT_SOCIALES_CIUDADANAS,
       PUNT_C_NATURALES,
       PUNT_LECTURA_CRITICA,
       PUNT_GLOBAL
FROM datos_icfes
WHERE PERIODO >= 20221
  AND (COLE_DEPTO_UBICACION = 'CUNDINAMARCA' OR COLE_DEPTO_UBICACION = 'BOGOTÁ' OR COLE_DEPTO_UBICACION = 'BOGOTA' );

# Consulta 1: Distribución de estudiantes por departamento y ciudad

SELECT COLE_DEPTO_UBICACION, COUNT(*) AS NUM_ESTUDIANTES
FROM datos_icfes
GROUP BY COLE_DEPTO_UBICACION
ORDER BY NUM_ESTUDIANTES DESC;

# Consulta 2: Análisis de Tendencias de Puntajes Globales a lo Largo del Tiempo

SELECT PERIODO, AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL
FROM datos_icfes
GROUP BY PERIODO
ORDER BY PERIODO;

# Consulta 3: Relación entre Nivel Educativo de los Padres y Puntajes de los Estudiantes

SELECT FAMI_EDUCACIONMADRE, FAMI_EDUCACIONPADRE, AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL
FROM datos_icfes
GROUP BY FAMI_EDUCACIONMADRE, FAMI_EDUCACIONPADRE;

# Consulta 4: Comparación de Puntajes en Colegios Bilingües vs. No Bilingües

SELECT COLE_BILINGUE, AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL
FROM datos_icfes
GROUP BY COLE_BILINGUE;

# Consulta 5: Influencia de Recursos Familiares en el Desempeño Académico

SELECT FAMI_TIENECOMPUTADOR, FAMI_TIENEINTERNET, AVG(PUNT_GLOBAL) AS PROMEDIO_PUNT_GLOBAL
FROM datos_icfes
GROUP BY FAMI_TIENECOMPUTADOR, FAMI_TIENEINTERNET;
